version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=adminmaster
      - POSTGRES_PASSWORD=adminmaster@master
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - pgnet  
  adminer:
    image: adminer
    ports: 
      - "8080:8080"
    depends_on: 
      - postgres
    networks:
      - pgnet          
volumes:
  postgres:
networks:
  pgnet:  